name: build package for rpm package

on: 
  issue_comment:
    types: [edited,created]

jobs:
  fedora-32:
    name: on Fedora 32
    runs-on: ubuntu-20.04
    if: github.event.comment.body == 'build on fedora 32' 
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Update apt repository
        run: sudo apt-get update -y
      - name: Install dependencies 
        run: sudo apt-get install -y make curl podman
      - name: build package
        run: make docker-build-fedora-32
  fedora-rawhide:
    name: on Fedora rawhide
    runs-on: ubuntu-20.04
    if: github.event.comment.body == 'build on fedora rawhide'
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Update apt repository
        run: sudo apt-get update -y
      - name: Install dependencies 
        run: sudo apt-get install -y make curl podman
      - name: build package
        run: make docker-build-fedora-rawhide
  centos-8:
    name: on centos 8
    runs-on: ubuntu-20.04
    if: github.event.comment.body == 'build on centos 8'
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Update apt repository
        run: sudo apt-get update -y
      - name: Install dependencies 
        run: sudo apt-get install -y make curl podman
      - name: build package
        run: make docker-build-centos-8        